src/drawing.rs
Small change to make behavior of the source and destination rectangles consistent.  Source rect was initially in UV coordinates while destination rect was in screen space.  This means if you wanted your source rectangle to have a width of 128x128, you had to enter 128/texture.width(), 128/texture.height() for the source width/source height.
Another option would be to update the documentation to say that these two are different.
=> Fix for #3.

Cargo.toml
[This issue](https://github.com/not-fl3/macroquad/issues/6)
=> Upgrade miniquad to 0.2.54 to fix issue with mising functions

examples/snake.rs, src/shapes.rs
added an example snake game, similar to the one in raylib, with a few more bells and whistles
added measure_text function in shapes.rs to be able to get the size of text (useful for drawing centered text and stuff)
=> added "snake" example and measure_text fn

src/texture.rs
Docs say it's in degrees but it's in radians.
=> DrawTextureParams docs fix

src/texture.rs
Fixed "Not such texture" to say "No such texture"
=> Fix typo in texture.rs

quad-gl/src/lib.rs
Without this fix:
With this fix:
=> Fix: _ScreenTexture dimensions not updated after window resizing

src/texture.rs
With this adjustment the setting of the **dist_size** is no longer mandatory if **source** is set.
=> dist_size no longer mandatory if source is set

src/input.rs
this function allows me to write the following code
```rust
if get_last_key_pressed().is_some() {
#[cfg(not(target_arch = "wasm32"))]
if is_key_pressed(KeyCode::Q) | is_key_pressed(KeyCode::Escape) {
*game_state = GameState::EXIT;
}else{
*game_state = GameState::GAME;
}
}
```
=> added possibility to detect if any key was pressed

examples/life.rs, examples/shadertoy.rs, quad-gl/src/lib.rs, src/lib.rs, src/window.rs
Now Color is 
```
pub struct Color {
pub r: f32,
pub g: f32,
pub b: f32,
pub a: f32
}
```
instead of 
```
pub struct Color(pub [u8; 4]);
```
Now we can destruct Color, access individual fields, keep >1.0 values inside Color struct etc.
While inside quad-gl still use [u8; 4], so this change should not affect perfomance at all. 
However it is a breaking change - some function signatures changed and `.r()` getter are now gone.
=> quad-gl: Switch Color from u8 to f32

quad-gl/examples/triangle.rs, quad-gl/src/lib.rs, src/prelude.rs
This allows building colors from 4 bytes in compile time.
```
assert_eq!(Color::new(1.0, 0.0, 0.0, 1.0), color_u8!(255, 0, 0, 255));
```
=> quad-gl: color_u8! macro

macroquad_macro/src/lib.rs
After this change this is allowed: 
```
#[mq::main("BasicShapes")]
#[macroquad(crate_rename = "mq")]
async fn main() {
}
```
This is the only way to use macroquad with Cargo.toml like this: 
```
[dependencies]
mq = {path = "../macroquad", package="macroquad"}
```
And also this change fix old standing bug with `#[cfg]` attributes on main, so this would also works:
```
#[macroquad::main("BasicShapes")]
#[cfg(target_os = "linux")]
async fn main() {
}
```
=> macroquad_macro: Support use case with renamed crate

quad-gl/src/lib.rs, src/lib.rs
The top-level docs look like this with these changes:
What do you think, @not-fl3?
=> Make a few types/mods reachable without prelude 

examples/screen_texture.rs, examples/shadertoy.rs, examples/texture.rs
Now you can run `cargo run --example=screen_texture` (for example), and it won't crash due to file-not-found.
=> fix the filepaths for images in examples

src/math.rs, src/prelude.rs
Now its going to be 
```
use macroquad::math::Vec2;
```
instead of 
```
use macroquad::math::glam::Vec2
```
And nothing is going to change for `prelude` users.
=> math: Re-export glam types

src/file.rs
Fixes #87 (_"FileError is returned by load_file but isn't public"_)
=> Re-export exec::FileError

Cargo.toml, examples/asteroids.rs, examples/snake.rs, examples/text_measures.rs, src/text.rs
I am not quite sure about merging this.
However, after this PR text rendering API will be a little more consistent.
Before this change Y in draw_text was a slightly incorrect top line of the future text. 
After this change Y in draw_text is a baseline of the text.
Pros: 
- Two consecutive calls `draw_text(0.0, 100.0, "A")` and `draw_text(10.0, 100.0, "j")` will draw both characters on the same line. 
- The bug with incorrect text positioning is fixed
- It is easier to figure out a background rectangle for a text
Cons: 
- All the current code using draw_text will be slightly broken
=> text: Change text measures logic

src/math.rs
Added `clamp` function in `src/math.rs`
made `example/tree.rs` look better by fixing screen ratio and adding lerped zooming with mouse wheel. 
Now it uses added `clamp`, so clamp is kinda tested.
note, that according to Rust standard libs, functions like clamp are actually made methods, actually there is f32::clamp, but it's unstable now. For better design mb we should have a trait or smth for feature like this?
=> added clamp to src/math.rs, polished examples/tree.rs

src/texture.rs
`Clone` would be nice when e.g. calling `draw_texture_ex` a lot, each with a bit more rotation.
Additionally i noticed there are lots of structs missing basic derives like Debug and Clone - should i add them everywhere where it makes sense or is there a reason for it (e.g. compile times)? I think it's commonly accepted in rust that public structs should have at least `Debug` where possible and usually `Clone` is very useful too.
=> Add Debug and Clone derives to DrawTextureParams

Cargo.toml, src/quad_gl.rs
Advisory about previous versions: https://rustsec.org/advisories/RUSTSEC-2020-0073.html
Note that cargo audit doesn't seem to warn about it but deps.rs does which makes projects depending on macroquad look insecure.
The png_codec feature was renamed here: https://github.com/image-rs/image/commit/e706bfbb29bc4bb5c54ac644f685bcfb87d8bb07
=> Update image to 0.23.12

src/models.rs
Wow,
This PR adds the functionally to `draw_spheres_wires`. Also was added `draw_sphere_ex` so you can specify the number of slices and rings when drawing the sphere.
This was made because drawing spheres can be really expensive, having this alternative way can help the user choose how good the spheres are drawn.
Normal `draw_sphere`:
Normal `draw_sphere_wires`:
`draw_sphere_ex` with rings = 6, slices = 8, draw_mode = DrawMode::Lines:
=> Add draw_sphere_ex and draw_sphere_wires.

src/models.rs
I had a chance to test the `draw_mesh` function today and noticed that in it's current state, it is not useable because the Mesh struct cannot be instantiated by user code due to the private fields. Here's a quick fix ;)
=> Fix models.Mesh not having public fields

examples/shadertoy.rs, src/material.rs, src/quad_gl.rs
Before this only `Texture` and `_ScreenTexture` were accessible from the shader, but now any user texture is accessible too.
=> material: Add ability to pass a textures to the shader

src/ui.rs
* fix double Enter
* fix bug when Backspace or Enter not typed, because of upped immediately (e.g. programming keyboard can do that) by using `is_key_pressed`
* use macro_rules to make code look prettier
duplicate of https://github.com/not-fl3/megaui-macroquad/pull/4
=> ui input: fix bugs

src/material.rs
=> fixed typo in material doc comment

examples/input_touch.rs, src/input.rs, src/lib.rs
Resolves #34 
Added multitouch support from miniquad. I tried several different ways to structure the API, and landed on `touches() -> Vec<Touch>` because it was simple, didn't have any borrowing/lifetimes, and contained all the information needed to use touchscreen input (including the ability to track touch ids for manual gesture inputs). 
Also, the default behavior in miniquad is to treat touch events like mouse events (i.e. whenever a touch event is fired, it forwards it as a mouse event). I preserved this behavior, but added a toggle to turn it off.
I tested this by running the `input_touch.rs` example in a browser--turns out touch events aren't raised in Windows desktop apps, even if you have a touchscreen. I'm guessing that's a feature that would have to be added to miniquad.
=> added touch support

src/input.rs, src/lib.rs
This can be useful in third-party UI libraries that run on the miniquad, like egui.
This is used in https://github.com/optozorax/egui-macroquad.
I don't quite sure that this is the right interface for a user. What do you think?
=> input: add function `repeat_all_miniquad_input`

examples/first_person.rs, src/input.rs, src/lib.rs
* Works on Windows
* Works on WASM
* Does not work on MacOS quite yet (due to set_cursor_grab/show_mouse implementations)
* Works on Linux (as tested by @not-fl3)
Fix #129
Adds support for grabbing mouse cursor.
Adds FPS example for use with new functions.
Re-exports set_cursor_grab and show_mouse from Miniquad.
=> Add Raw Mouse Motion Event Support By Adding Capture Mouse Support

README.md, examples/camera_transformations.rs, examples/raw_miniquad.rs, examples/shadertoy.rs, particles/src/lib.rs, src/camera.rs, src/experimental/collections.rs, src/experimental/coroutines.rs, src/file.rs, src/input.rs, src/lib.rs, src/prelude.rs, src/quad_gl.rs, src/telemetry.rs, src/text.rs, src/texture.rs, src/time.rs, src/ui.rs, src/ui/style.rs, src/ui/widgets/popup.rs, src/window.rs, tiled/src/lib.rs
In addition to this PR, there is some more things that I think should be adjusted but it is in function and constant names and thus may cause some breakage.
The following typos was found in code, but should be addressed in a separate PR:
```
boundries => boundaries
LinearTweanFuture =>  tween
Aligment => Alignment
delimeter => delimiter
snapshoter => snapshotter   ?
```
=> fix some typos in comments

src/experimental/animation.rs
It is useful to have a clone on this type so it can be used as a prototype for creating instances of an animated object.
=> Add missing Clone derive to AnimatedSprite

examples/life.rs, examples/platformer.rs, examples/post_processing.rs, examples/shadertoy.rs, src/drawing.rs, src/models.rs, src/quad_gl.rs, src/text/atlas.rs, src/texture.rs
No more miniquad context in the public API. 
This is a breaking change, but this was supposed to happen long long time ago
=> texture: Remove miniquad context from public API

src/prelude.rs, src/texture.rs
These are the changes in separate commits:
- image::ImageFormat enum is exported in the prelude, since it was not really accesible before.
- Each method is now documented, plus some examples and I moved the constructors up.
- Run rustfmt on the whole library.
The examples pass unit testing. More can be added later if you like them.
I have some doubts regarding Context. The way I create it works in the examples but I don't think it's supposed to be used like that in real programs...
I think it would be good if I add documentation to some types in miniquad too.
=> Add documentation for Texture2D and Image.

src/lib.rs
This can be used to automatically take screenshots of the examples, or potentially in CI. This feature could be used by `RUSTFLAGS='--cfg one_screenshot' cargo run --example tree`.
=> lib: add compile-time option to save screenshot

Cargo.toml, src/audio.rs
I think using `rodio` for audio was a mistake, it just wants too much code to be involved in the process (way more than the whole macroquad with all the dependencies): 
<details>
<summary>`cargo tree` without rodio</summary>
```
macroquad v0.3.2 
├── bumpalo v3.6.1
├── fontdue v0.4.0
│   ├── hashbrown v0.8.2
│   │   └── ahash v0.3.8
│   │   [build-dependencies]
│   │   └── autocfg v1.0.1
│   └── ttf-parser v0.8.3
├── glam v0.14.0
├── image v0.23.14
│   ├── bytemuck v1.5.1
│   ├── byteorder v1.4.3
│   ├── color_quant v1.1.0
│   ├── num-iter v0.1.42
│   │   ├── num-integer v0.1.44
│   │   │   └── num-traits v0.2.14
│   │   │       [build-dependencies]
│   │   │       └── autocfg v1.0.1
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.0.1
│   │   └── num-traits v0.2.14 (*)
│   │ …
```
=> audio: Disable audio on android

src/ui.rs
* Added method `set_input_focus` to `WindowContext`
* Added method `clear_input_focus` to `WindowContext`
Should setting the focus also set the window focus to the containing window, if any?
=> Add setter and clear methods to UI

src/ui.rs
Trivial change, but it allows access to the StyleBuilder in the docs.
=> Re-export StyleBuilder to be visible in documentation

examples/camera.rs
This just removes a typo from `examples/camera.rs` where a piece of code was duplicated, causing an unused camera to be constructed.
=> Remove an unused code block from camera example

Cargo.toml, src/lib.rs, src/quad_gl.rs, src/window.rs
A new macroquad::window function, allows to catch a panic and render a panic message + backtrace on the screen
=> window: set_panic_hook

examples/exit_dialog.rs, src/input.rs, src/lib.rs
This patch proposes a possibility for user to handle 'quit' event.
It is also required to change `miniquad::conf::Conf` struct to contain `pub handle_quit_event: bool` field.
I use this to correctly terminate networking before the quit.
=> Add possibility to handle 'quit' event in main loop

src/input.rs
It's confusing to refer to the button as "key".
=> Replace key with button in is_mouse_* docs

examples/back_to_the_future.rs, examples/back_to_the_future_coroutines.rs, src/exec.rs, src/experimental/coroutines.rs, src/file.rs, src/lib.rs, src/window.rs
fixes #286
In the future (haha), when we get a pending future, we could even consider sleeping/yielding the current thread until a waker has been invoked.
Some background on why I hit this:
I had to wait for a callback in some js code that I invoked. I didn't want to just loop until the value is created (not even sure that would work), so I tried implementing a future. I did a trivial one first, that didn't use wakers and just returned pending as long as there was no value. That just caused the entire macroquad state to get stuck somewhere, since I wasn't using the `ExecState` datastructure. I didn't know about that yet, so I tried implementing a waker system by sending a boxed waker to js and creating a wasm callback that js can call in order to wake the waker. So good so far, but then …
=> Allow users to use arbitrary futures

src/experimental/coroutines.rs, tests/coroutine_pause.rs
Syntetic tests: [tests/coroutine_pause.rs](https://github.com/not-fl3/macroquad/blob/coroutine_pause/tests/coroutine_pause.rs)
Less syntethic test: 
https://user-images.githubusercontent.com/910977/132287061-f7f9c54b-fd4c-4a73-8e40-54b7d2057b6b.mp4
This change allows switching coroutines into a "manual" polling mode. 
Each coroutine in "manual" mode has its own timeline and could be advanced with given delta time - so they are not dependent on real frames deltas. It may be helpful for simulation pause, "fixed" delta time simulation etc.
@oli-obk The thing with pausable coroutines I was talking about in your futures PR.  It works! 
Ended up with some `get_context` calls inside `wait_seconds`, but still better than passing context through unsound transmuting
=> coroutines: Support pausable coroutines

src/experimental/camera/mouse.rs
- I changed the variable name for `mouse_pos` to `center` because I think using `mouse_pos` suggests that the mouse position should be used, even thought that's not necessary
- I changed `impl Into<Camera2D> for Camera` to `impl Into<Camera2D> for &Camera`, so it doesn't have to be cloned on each frame
- I derived `Copy` for Camera because it's trivial to do
- I improved the documentation with some suggestions and examples
=> Improve docs and fix Into<Camera2D> for `experimental::camera::mouse`

src/lib.rs, src/text.rs, src/window.rs
Fixes https://github.com/not-fl3/macroquad/issues/30
This PR worked in my very contrived scenario so what I would encourage everyone who had the problem in #30 to do is test this out locally and report errors here! I have very likely missed places where the raw screen size is used without conversion. Add this to your `Cargo.toml` to test: `macroquad = { git = "https://github.com/dotellie/macroquad.git", branch = "high-dpi" }`
Before
After
Funny thing is actually that the circle was also affected by this problem as you can see in those screenshots 😅
=> Add high-dpi support

src/math/circle.rs
The point in circle calculation was checking if the incoming point was *outside* the circle instead of inside.
=> Fix: incorrect Circle::contains check

src/lib.rs
The `logging` mod exported every logging macro except `trace`
=> Export trace logging macro

src/window.rs
Exposed miniquad's `set_window_size` as a function. I'm using this to test that my game runs on different phone sizes correctly without having to rebuild my game every time.
While testing this on Windows I immediately noticed that Windows doesn't always respect the value that you feed it. In my case I fed it a value of 3040x1440 (the screen size of a Galaxy Note 10+) and windows only gave me 3040x1061. This is probably dependent on the monitor layout. 
Because of this inconsistency (and presumably many more OS-specific quirks) I decided on a very conservative name and a explanation on the behavior. I also didn't want to update `context.screen_width/height` immediately because then the value would be `A -> Requested B -> frame end -> Actual B`, which seemed more confusing to me.
=> Added window::request_new_screen_size

src/math/circle.rs
* Updated Circle struct to make x, y and r public which addresses #384
* Added in Clone, Copy, Debug, Default, PartialEq based on Rect as needed to be able to copy/clone the struct and went for matching Rect.
=> Updated Circle struct to allow for clone/copy/debug and make fields public

src/ui/widgets/button.rs
This PR adds a `selected` method to the UI Button, such that the
selected styling in the skin can be applied when the button is active.
Please shout if this isn't done as you'd like - I'm very new to Rust!
=> Add `selected` to `Button`

src/text.rs
Why:
The dpi scaling is not applied in the measure_text function to resulting text dimensions, but in the draw_text_ex it does.
How:
Just apply a dpi scaling in the measure_text function by analogy with the draw_text_ex function.
Issue: https://github.com/not-fl3/macroquad/issues/373
=> Fix: incorrect text dimensions from measure_text on custom dpi

src/lib.rs
Mouse button events were not sent to subscribers while the mouse was grabbed. This change makes the mouse button events visible when calling `utils::repeat_all_miniquad_input`.
=> Pass grabbed mouse button events to subscribers

src/exec.rs, src/experimental/coroutines.rs, src/lib.rs, tests/coroutine_pause.rs
with this you can return values from coroutines like this
```rust
#[macroquad::test]
async fn coroutine_value() {
let mut coroutine = start_coroutine(async move {
next_frame().await;
1
});
coroutine.set_manual_poll();
assert_eq!(coroutine.retreive(), None);
coroutine.poll(0.0);
coroutine.poll(0.0);
assert_eq!(coroutine.retreive(), Some(1));
}
```
=> Allows coroutines to return values

src/experimental/coroutines.rs, src/experimental/coroutines/generational_storage.rs, src/telemetry.rs, tests/coroutine_pause.rs, tests/coroutine_values.rs
Now coroutines reuse memory from older, finished coroutines and therefore starting new coroutines doesn't leek the memory.
There is still a way to leak the memory, though - if coroutine return the value and that value is never retrieved - macroquad will keep this value forever. The only fix available - make coroutines non-copy and mark them the value "unwanted"  in the Drop.
Not too much of an issue - the intention of returning a value from a coroutine - is always to retrieve it (hopefully).
cc @nobbele
=> coroutines: Fix memory leak

physics-platformer/src/lib.rs
A fix for https://github.com/fishfight/FishFight/issues/135.
I've only tested it with FishFight, but it appeared to fix the problem.
=> Remove Collisions With Out-of-Bounds Tiles

src/math/rect.rs
I think a center() function for the Rect, could be useful in many cases.
then we don't have to type this every time:
`let center = rect.point() + rect.size() * 0.5f32;`
=> math: Rect::center

particles/src/lib.rs
When calculating matrix index from Particle AtlasConfig, to get row index, array index needs to be divided by width, not height
=> Fix AtlasConfig wrong matrix index calculation

profiler/src/lib.rs
Currently profiler displays frame time as 0.016ms instead of 16ms
=> Fix wrong time units in profiler

particles/src/lib.rs, particles/src/particles.glsl
These 2 commits can be applied independently (sorry for batching them into one pr)
Currently, EmmiterConfig's `shape` field can be set to `EmmisionShape::Rectangle`, but what you get is a square.
Adding `aspect_ratio` seems like the simplest solution to have rectangles.
Since this commit modifies rectangle shape to `ParticleShape::Rectangle{aspect_ratio: f32}` it is a **breaking change** for those who explicitly set `shape: ParticleShape::Rectangle`. Hopefully, this is a rare case since it is the default setting.
This adds the following params to EmitterConfig:
```
initial_rotation: f32,
initial_rotation_randomness: f32,
initial_angular_velocity: f32,
initial_angular_velocity_randomness: f32,
angular_accel: f32,
angular_damping: f32,
```
To quickly hack this, I've used the z coordinate of …
=> Particles: fix ParticleShape::Rectangle and add rotation params to EmmiterConfig

tiled/src/lib.rs
When drawing a tile layer, macroquad tries to batch draw calls, but batching is reset every time the tile tileset changes.
This means that for drawing a single layer, we need `number_of_tilesets ..= number_of_tiles` draw calls (eg. if all odd tiles are from one tileset, and even from a different one, we will have a draw call for each tile).
Before drawing tiles, we separate them by tileset. This enables macroquad to batch all tiles from one tileset together, so we will always have `number_of_tilesets` draw calls.
=> Tiled: optimize draw calls batching

tiled/src/lib.rs
This line (which I wrote :) ) panics when user passes source rectangle that is out of bounds
=> Fix panic when drawing out of bound tiles

particles/src/lib.rs
If `lived` is not limed to `lifetime`, condition on line [835](https://github.com/not-fl3/macroquad/blob/b37e40305e6eda6848d57077e769c9f558dd0af5/particles/src/lib.rs#L835) can be true, which in turn causes emitting of new, unwanted, particles.
This happens for example if `explosiveness: 1.0, lifetime_randomness: 0.5`
=> Limit particle lived timer

particles/src/lib.rs
Limiting `lived` introduced a new problem: particles were not removed until the end of `config.lifetime` (instead of their individual lifetimes)
=> Fix particle's lifetime

src/audio.rs, src/quad_gl.rs
Just switched the places of byte sizes in the message
=> Fix wrong warn message for set_uniform

src/text.rs
Fixes #487, not sure if this is the right change but it seems like this is more correct.
After this change both Firefox and Windows display the same font size when the reproduction repo is run.
=> Fix font size scaling in `draw_text_ex`

src/text.rs
follow on to #488. Sorry, forgot that this also needed to be changed in `measure_text` as well
=> fix font size scaling in `measure_text`

examples/text.rs, src/text.rs
This PR fix issue  #393.
* Add rotation parameter to draw_text_ex.
* Add a rotating text into text example.
Note: I think adding a new method to retrieve the text center could be convenient. I will try to add one in a next PR unless you want it in this one.
=> Add rotation to draw_text_ex method

physics-platformer/src/lib.rs
After trying out examples I noticed a bug (#459 ) in the platformer example.
In mentioned issue was mentioned latest code change when the bug appeared. My guess was that the last row of tiles is not taken into an account and increasing layer_height by one fixed it.
=> FIX: falling trough lowest row of solids

particles/src/lib.rs
This change https://github.com/not-fl3/macroquad/pull/458 introduced a regression: `examples/particles_example` got broken.
I am not quite sure how it should be properly fix, so for now I'll just rollback the change to get the example alive again. 
I guess something need to be done with https://github.com/not-fl3/macroquad/pull/461 as well? 
cc @vdrn
=> particles: fix particles lifetime

examples/text.rs, src/text.rs
Follow #415 
- Add get_text_center method helper to get the center of a text block.
- Show text rotation examples.
=> Add get_text_center method and show text rotation examples

src/audio.rs
This fixes https://github.com/not-fl3/miniquad/issues/317
The build failure was caused by the missing `is_loaded` function in the dummy audio implementation. 
I'm not sure if returning `true` would be a better choice in case a project decides to wait for it to return true. 
I also added `delete` to prevent similiar problems in the future.
=> Fix macroquad not building under wasm when default features are disabled

src/text.rs
So far `load_ttf_font` would panic when called on a non-existing file. This seemed counter intuitive to me as it returns a Result. 
So i changed it to return an error if it fails to load the file. 
Right now it still can crash when being called under wasm, but this should be resolved with this https://github.com/not-fl3/miniquad/pull/323 merge request, and then the behavior should be consistent across all plattforms.
=> Make load_ttf_font failures recoverable

src/shapes.rs
I added a function that renders a rectangle with a position (centered), a rotation (degrees), and a size
Right now, the only way to rotate a quad is using `draw_poly` so I created this function
I created a transformation matrix and multiply it to the vertices
=> Added `draw_rectangle_pro`

src/ui/widgets/editbox.rs
This shows android virtual keyboard when an input has focus.
If the input blurs the keyboard will get hidden again.
Or is there any reason this is not already implemented? There is no input focus event (I am aware of) so this cannot be done from outside.
=> show/hide android virtual keyboard on input focus/blur

src/ui/widgets/editbox.rs
This condition prevents setting the cursor after the text in single and multiline editbox.
I tested the fix on wasm, linux and android.
=> remove condition that prevents setting the cursor after the text

src/text.rs, src/ui/render/painter.rs
This takes care of the issue on TreeNode and probably in other places as well. It will fix #530.
I think it is a good idea to merge this like the last occurrence but also looks like it is worth exploring if `offset_y` in `TextMeasures` should be DPI aware instead.
=> Further fix label alignment on high-dpi displays

src/ui/widgets/editbox.rs
On at least some platforms, pressing backspace sends a key event for the backspace character as well as a backspace event, which was causing deleting characters with the backspace key to not work properly in the editbox widget.
Fixes #552
=> fix backspace handling in editbox widget

src/ui/widgets/editbox.rs
Followup to #564 adding the keycode for backspacing on a Macbook, which fixes #552.
=> Fix backspace handling in editbox for macbooks

src/ui/widgets/editbox.rs
Another followup to 3b141dc. Replaces the individual keycode checks in editbox.rs with a blanket check for ascii control codes. This cleans up the previous code and also fixes the tab key behaving incorrectly in inputboxes.
=> Replace list of keycodes to ignore in editboxes with is_ascii_control()

src/models.rs
The functions `draw_affine_parallelogram` and
`draw_affine_parallelepiped` can be seen as generalizations of `draw_plane` and `draw_cube`, though some better interfaces with textures (uv coordinate, texture per face) and colors are probably still necessary.
=> Add functions to draw parallelograms and parallelepipeds in 3D space

src/text.rs, src/text/atlas.rs
Simplest way to add filtering mode support for `Font`.
We could perhaps even go a step further and remove the `filter` field from the Atlas itself and just use the one on Texture2D.
That way we could bring back the commented out `Font::texture() -> Texture2D` instead and change filtering level (and more).
=> Add filtering mode for `Font` and `Atlas`

tiled/src/error.rs, tiled/src/lib.rs, tiled/src/tiled/layer.rs
Here an image layer (the orange cloud) is added with some offset and transparency in tiled as shown.
code:
```rust
#[macroquad::main("Typewriter")]
async fn main() {
// load tiled-map.json, textures..etc
...
loop{
...
tiled_map.draw_tiles("platforms", dest_rect, None);
tiled_map.draw_imglayer("bgimage", dest_rect, None);
...
}
...
}
```
=> added draw_imglayer()

particles/src/lib.rs
Currently, the description of `EmitterConfig.amount` states `Amount of particles emitted in one emission cycle.`, however it only relies on comparison of `time_passed` to `EmitterConfig.lifetime`.
Due to this changing the `EmitterConfig.lifetime_randomness` configuration parameter to anything other than 0. will instead lead to incorrect amount of particles spawning when using the `EmitterConfig.one_shot` setting.
This pull request changes it so that the amount of particles emitted per one such cycle is always correct.
=> Spawn only `amount` particles per cycle

src/shapes.rs
Before this commit, the `draw_poly` function iterates over the sides using `0..sides + 1`, and since `sides` is a u8, drawing 255 sides would be an integer overflow. This commit changes `0..sides + 1` into `0..=sides`.
=> Allow for drawing polygons with 255 sides.

examples/snake.rs
Hi!
I found two issues with the snake.rs example, which I addressed in this pull request:
- Game over text was not properly centered
- Implements navigation lock between two update cycles. Otherwise, the direction can be changed multiple times before the snake is updated, which can results in an illegal turn in the opposite direction.
Thanks,
Auberi
=> Tweaks and bug fixes for snake.rs example

particles/Cargo.toml
macroquad-particels depends on macroquad with default features.
So  if you use macroquad without the sound feature and you also use macroquad-particels the sound feature is still enable. 
This is for example problematically if you use alternative sound library like rodio. Since both depends on alsa at different versions, alsa can not be linked (you can only link one version of a c library at the same time).
So you can not use rodio and  macroquad-particels together currently.
Hit this issue at https://github.com/LuckyTurtleDev/mission2teegarden-b
Since macroquad-particels does not use sound, I would proposed to simple disable default-features.
=> particles: disable default features of macroquad

src/lib.rs, src/texture.rs
Hello,
When I was perf-ing my game I noticed function `same_thread` is eating significant amount of my cpu along with `draw_texture_ex`. I modified the code to perform better, for `same_thread`, thread local is used to cache it. I do not know how good this performs on all platforms but on linux it makes the check almost free. For the texture render, I noticed calls to width and height are internally calling methods on trait object so rust cannot know if its safe to reuse the values in other calls, I also eliminated texture clone which removed atomic operations.
=> improving performance of getting the context and texture rendering

src/text.rs
Wrap fontdue::Font into Arc to make ::Font relatively cheap to clone again.
=> Wrap fontdue::Font into Arc

src/experimental/animation.rs
Added this method to implement a state transitioning system, in where a sprite can only change its animation when it's fully ended.
=> Added AnimatedSprite::is_last_frame

src/texture.rs
Changed get_screen_data() to use a managed macroquad texture with `store_texture` instead of `from_miniquad_texture` to fix the memory leak mentioned in #655.
I'm not sure if there was a specific reason it was using `from_miniquad_texture` before but I didn't notice any difference in behaviour.
=> Fixed memory leak at get_screen_data()

src/shapes.rs
Solid ellipses and lined ellipses as proposed in #575 
This implementation draws a polygon with 20 sides just like how circles are drawn, but this one can be stretched and rotated.
=> draw_ellipse and draw_ellipse_lines

src/models.rs
It always bugged me that you couldn't move the grid in raylib. I'd considered also adding the ability to do like an XY grid, XZ grid, YZ grid, but couldn't think of an intelligent way to do it.
Maybe setting an `up: Vec3`?
=> Add draw_grid_ex, and have draw_grid use that with vec3(0,0,0)

src/ui.rs
When creating a window with `movable` = `false`, the layout of components is a bit off. This is caused by the call to `set_position()` here:
https://github.com/not-fl3/macroquad/blob/d8e2f9d2128d9bb14a22f225efebfbf41f5ec979/src/ui.rs#L795-L797
..which ends  up setting the position itself as expected, but failing to adjust for window margins for the cursor area.
=> Consider window margin when setting position

examples/arkanoid.rs, examples/platformer.rs
Commit 3887953 inverted the Y-axis; this fixes the two examples where it matters.
=> Display `arkanoid` and `platformer` the right way up (#667)

src/texture.rs
This method raises this error on web:
> PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: IoError(Error { kind: Unsupported, message: "operation not supported on this platform" })), location: Location { file: "{...}\\macroquad-0.4.4\\src\\texture.rs", line: 253, col: 10 }, can_unwind: true }
Added a doc comment to explain that this method isn't available for wasm.
=> Add warning doc for export_png

src/quad_gl.rs
When setting the material using gl_use_material, if the same material is passed, there is no need to break batching and increase draw calls. It seems that not performing break_batching when the pipeline is the same would be better in terms of performance.
=> Change to break_batching update only when pipeline's are changed

src/texture.rs
Fixed a bug in the draw_texture_ex function where the width and height values were not updated to the width and height of the batched_texture, causing the values of the vertices to become incorrect.
=> fix texture size bug when using batched_texture

src/color.rs
Add details about expected values and include some examples in docs.
=> Add more documentation to color.rs

src/ui/render/mesh_rasterizer.rs
This change addresses a bug that appears to prevent new drawlists from being pushed if the most recent drawlist has no texture. 
I believe the intention of the code is to only prevent new drawlists if the most recent drawlist does have a texture and its the same as the command
This closes https://github.com/not-fl3/macroquad/issues/664
=> fix bug with checking last drawlist was texture

src/shapes.rs
Two vertices had the same uv coordinate, which makes no sense. It now has the same uv coordinates as draw_rectangle()
=> fixed a bug in draw_rectangle_ex()

tiled/src/lib.rs
As per tiled's [Layer](https://doc.mapeditor.org/en/stable/reference/json-map-format/#layer) JSON doc.
=> fix: objectlayer -> objectgroup for layer case

src/window.rs
macroquad already has screen_width() and screen_height().
dpi_scale() is inaccessible though.
=> feat(Window): expose screen_dpi_scale()

src/texture.rs
Adds blend() and overlay() fns to Texture2D::Image. I needed this type of fn for a project where I was programmatically generating images to be used as game assets [like adding a cloud layer onto an image of a planet], and I figured it was worth seeing if you wanted it added to the repo. 
The blend() fn is loosely based off of [OpenCV saturated image blending](https://docs.opencv.org/4.x/d0/d86/tutorial_py_image_arithmetics.html), and the overlay() pretty much just overlays the input image overtop of the original image, accounting for transparency.
I've never committed anything to this repo before so let me know if any changes are needed (for instance, I have an image_manipulations.rs example file I used to test these fns, but it is not included in this pull request).
=> Adds blend() and overlay() functions to Texture2D::Image

src/texture.rs
This allows user to update a texture from an array u8. If you have a buffer from some crate now you can update a texture without depending on macroquad image.
This change affects me directly and thus I implemented it. I hope this is compatible with macroquad way of doing things.
=> Added update_from_bytes method to Texture2D

src/shapes.rs, src/text.rs, src/ui/render/mesh_rasterizer.rs
replace std::f32::{EPSILON, MAX} with f32:: as per rust docs recommendation (old way is deprecated)
=> replace std::f32::{EPSILON, MAX} with f32:: as per rust docs recommendation (old way is deprecated)

README.md
Just updates the README to point to the right docs on docs.rs for the current version.
=> Update badge in README to docs to link to 0.4.5

particles/src/lib.rs, src/camera.rs, src/texture.rs
* Fix issue with RenderTarget leaking memory by adding a drop impl, reported in issue #635
The memory leak issues just floating around were bothering me, and seemed simple enough to fix so figured why not :)
I also looked at #628 but couldn't actually reproduce the issue, so left that one alone for now.
=> Fix issues with RenderTarget leaking memory.

src/text/atlas.rs, src/texture.rs
* Fix issue with Font Atlas leaking memory by adding a drop impl, reported in issue #627
Split this out from the other PR so at least this change would go in, since it seems mostly unproblematic :)
=> Fix issues with Atlas leaking memory.

Cargo.toml
Updates `glam` to version `0.27`.
My main motivation here is to at least hit `0.24` for the convenience of the `saturating_*` functions on the integer vector types.
I get a few unrelated test failures locally so I can't 100% verify that this is ok, but output is at least identical to running tests on  `master` which is promising. For completeness, the failures are the coroutine tests as noted at #693, and a number of doc tests. Running anything locally with this build hasn't caused me any problems on either MacOS or Linux X11.
=> glam => 0.27

src/models.rs
Adds functions to draw cylinders.
Can also be used for cones by setting on of the top or bottom radius to zero.
=> Implementation of functions to draw cylinders and cones

macroquad_macro/src/lib.rs
Fixes #626 by allowing that the main function with the `macroquad::main` attribute macro is public.
=> Support public functions in `macroquad::main`

examples/custom_material.rs, src/lib.rs, src/material.rs, src/quad_gl.rs, src/tobytes.rs
Before this PR, it was impossible to create macroquad material with an array as an uniform type. 
Now it is possible: 
```
let mat_with_array = load_material(
ShaderSource::Glsl {
vertex: VERTEX,
fragment: FRAGMENT_WITH_ARRAY,
},
MaterialParams2 {
uniforms: vec![UniformDesc::array(
UniformDesc::new("test_color", UniformType::Float4),
10,
)],
pipeline_params,
..Default::default()
},
)
```
To reduce an impact of a braking change, `load_material` signature changed:
```diff
pub fn load_material(
shader: crate::ShaderSource,
-     params: MaterialParams,
+     impl Into<params: MaterialParams>,
) -> Result<Material, Error>;
```
Most of the old code using load_material should keep working, while now it is possible to use `MaterialParams2`, the same struct, but with a complete `UniformDesc`. …
=> Support uniform arrays

src/text.rs
This PR adds two functions for drawing multiline text that breaks on newlines. The new `draw_multiline_text` and `draw_multiline_text_ex` functions mirror the existing signatures of the `draw_text` and `draw_text_ex` functions. 
A different option would be to add a field `pub is_multiline: bool` to `TextParams`, which would avoid having two new functions, but that would be a breaking change and would have to wait for 0.5.
=> add `draw_multiline_text` and `draw_multiline_text_ex`

src/shapes.rs
Removes the private `draw_poly_lines_from_to` function which had misleading argument names and uses `draw_arc` instead as implementation for `draw_poly_lines`.
Fixes #756.
=> fix missing lines bug in `draw_poly_lines`

examples/custom_material.rs, examples/screen_texture.rs, examples/shadertoy.rs, src/material.rs, src/prelude.rs, src/quad_gl.rs, src/tobytes.rs
`load_material` use miniquad's PipelineParams, so trying to hide raw miniquad's UniformDesc struct doesn't really make much sense. 
And the attempt to make the change backwards-compatible with load_material receiving both the old style and the new style arguments was futile anyway - `impl Into<MaterialParams>` is not quite API compatible with `MaterialParams` anyway.
So, let's just suffer from a breaking change, but not have `MaterialParams` and `MaterialParams2`. Its semver-legal for 0.4, right?
=> Fix compilation error with load_material

Cargo.toml, src/experimental/scene.rs, src/experimental/scene/arena.rs
Honestly, `scene` overall needs to go. It should be either heavily refactored or be extracted into a separate crate. Having the whole fairly big dependency just for `scene` is a bit of an overkill.
=> experimental/scene: remove bumpalo dependency

src/shapes.rs
Before: 
After:
Short arcs before might not display properly depending on the exact ratio of each step length and the arc span. This adjusts the length of each segment so it will always fit perfectly.
Also uses direct draw calls so the edge is always a straight line to the center of the circle.
=> Fix arc exactly matching destination given angle

src/color.rs
Fixes #765 by swapping the two words.
=> fix swapped words in `Color`documentation

src/models.rs, src/prelude.rs, src/quad_gl.rs, src/ui.rs, src/ui/render/mesh_rasterizer.rs
Also Remove VertexInterop thing for good.
People do ask for extra attributes quite often, and I do not thinkg that slightly larger memory footprint will hurt anyone too much.
=> graphics: Add Normal vertex attribute

src/lib.rs, src/text.rs, src/texture.rs
=> added ability to change default texture filter

src/camera.rs
This PR does two changes.
First corrects the Camera3D's documentation for fovy. The docs said it is in degrees, however the code expects radians.
The second one changes the default Camera3D's fovy to be the correct probably intended value. It was 45, which is not normalized radians, thus probably not intended. Now it is 45°. This is a breaking change as the default is different. (By normalizing 45 radians we get something around 58 degrees)
=> Consistent Camera3D's Fov angle units.

src/ui/widgets/editbox.rs, src/ui/widgets/editbox/text_editor.rs
This PR trades UTF8 support for one extra memory allocation per input field.
Before, all UI code was using `&mut String` and was operating right on the user data, reallocating memory only when neccesary. After, each input field copies String into a Vec<char>, and than copies the data back. 
Technically, all the UTF8 bugs are fixable without Vec<char>, we just need to make a very clear distinguish for "cursor pointing into a character"/"cursor pointing into a byte". With a lot faster navigation/slicing of Vec<char> than a a char's iterator from a string, perfomance/memory tradeoff is not super obvious, and with implementation being so much easier with a Vec<char> - let's chose this route.
=> ui: UTF-8 support in input fields

tiled/src/lib.rs
Current `macroquad_tiled` implementation lookups the tileset for a tile by searching via this predicate
```rust
tile >= tileset.firstgid && tile < tileset.firstgid + tileset.tilecount
```
before then converting from `GID` to a tileset-local ID. This is not entirely correct, because the GID is also used to store tile flip flags (https://doc.mapeditor.org/en/stable/reference/global-tile-ids/#tile-flipping).
This causes the above check to fail and all flipped tiles get filtered off.
* When looking up the tileset the tile flip flags are masked off
* Since exposing the raw tile id will be backwards-incompatible they are masked off when constructing the `Tile` struct
* 3 new fields have been added to `Tile` 
* I HAVE NOT updated the rendering code, but can if requested
* I have done small local …
=> Add support for tile flip flags

tiled/src/lib.rs
When a tileset is "external" (e.g. passed via `external_tilesets` to `macroquad_tiled::load_map`) -- it doesn't get properly incuded in the `raw_tiled_map` field of the `Map` struct (as completely empty tilesets).
This PR fixes it by simply injecting `map_tilesets` in the returned value. As it is pretty much the list of all the tilesets parsed and resolved.
Unless someone relied on external tilesets being stored as empty tilesets (which this PR assumes is highly unlikely), this change is backwards compatible.
=> Fix external tilesets not being stored correctly

Cargo.toml, src/texture.rs, src/texture/slotmap.rs
This showed a slight improvement in compile time for me, as `slotmap` is only used in `texture.rs` and most of it is not needed and many things can be simplified based on the limited use case.
=> replace slotmap dependency with reduced local version

src/ui.rs
This removes two of the compiler warnings when building `macroquad`.
=> use `if let` instead of iterating over `Option`

src/audio.rs, src/lib.rs, src/models.rs, src/quad_gl.rs, src/text.rs, src/texture.rs, src/ui/canvas.rs, src/ui/cursor.rs, src/ui/style.rs, src/ui/widgets/button.rs, src/ui/widgets/editbox/text_editor.rs, src/ui/widgets/texture.rs, src/ui/widgets/window.rs
A first step towards making clippy complain less: this PR removes unnecessary casts to the same type, unused lifetimes, changes `#cfg(all(feature = "audio"))]` to `#[cfg(feature = "audio")]` and `!CONTEXT.is_none()` to `CONTEXT.is_some()`.
I have not focused on the `style` clippy warnings, as they are often personal preferences, so the changes in this PR should be trivial simplifications only.
=> fix several clippy complexity warnings

tiled/src/lib.rs
The previous tile flip flag extraction & masking didn't update all parts of logic. The `attrs` field initialisation was left out by accident. Which made `macroquad-tiled` incorrectly set it to empty string for flipped tiles.
I simply moved flag extraction before it and now it works in my local repository
=> Fix another tile flip flag oddity

Cargo.toml
Should be unproblematic because `fontdue`, unlike `image` and `glam`, is purely an internal dependency and is not publicly reexported.
=> bump fontdue version

tiled/src/tiled/layer.rs
The `Layer` struct used a `HashMap` to encode the properties instead of `Vec<Property>`. Which made `macroquad_tiled` crash when it tries to parse a map where there is a layer that has custom properties. This is because they are stored the same way as everywhere else.
* Simply replace the type with `Vec<Property>`
* Also added a link to the `tiled` docs for the `Layer` struct
=> Use the correct type for layer properties

src/quad_gl.rs
The cost of breaking the batching in macroquad is too big:
* Each unbatched call creates a `410kb` sized buffer on the CPU
* Each unbatched call creates a new buffer on the GPU
This PR aims to eliminate the big allocations on the CPU side of things to reduce the code of breaking the batching.
The fix is based on the assumption that a ~1mb sized batch is very rare and that most of that 1mb is unused space.
Instead of using a buffer per draw call, the implementation uses a big contigious buffer. Each DrawCall instead stores `(start, len)` in that buffer, essentially acting as a slice
=> Armotize cpu drawcalls

src/experimental/scene.rs
`get_scene` is called in quite a few places. The most notable place where it gets called is `get_frame_time`. 
It has been discovered, that calling `get_scene` is quite costly. Which by transitivity makes `get_frame_time` costly.
This is because in `get_scene`, `SCENE.get_or_insert(Scene::new())` is used. This causes a temporary `Scene` struct to be constructed each time the `get_scene` call is made as Rust eagerly evaluates function arguments.
This is a problem, because `Scene::new()` calls `Arena::new()`. `Arena::new()` calls `vec![Vec::with_capacity(ARENA_BLOCK)]` (aka allocates memory). This essentially causes `get_scene` (and `get_frame_time`) to constantly allocate and deallocate memory.
The fix is to simply replace `get_or_insert` with `get_or_insert_with`, which allows …
=> Reduce the cost of get_scene

tiled/src/tiled.rs
This PR fixes closes #701. This described crash happened, because `macroquad-tiled` was using a duplicate empty `Layer` struct for Tile's `objectgroup` field.
Simply removing that duplicate type and importing the correct one from `layer.rs` makes the map successfully parse. It also seems that all the required fields for reading colliders are already present.
This change is backwards compatible as it only "adds" stuff, not removing anything.
=> tiled: fix crash from colliders

src/audio.rs
This PR fixes a memory leak in macroquad, fixing #628
It seems the `Sound` struct simply wasn't using `QuadSndSoundGuarded`. Putting this struct into the `Arc<..>` makes the sound and its mem free correctly thanks to Arc's automatic drop call. After the patch and testing with the code from the issue -- the leaks were gone.
I couldn't trace why that wasn't done, but just in case I tested this fix with the following macroquad code
```rust
use macroquad::{audio::{load_sound, play_sound_once}, prelude::*};
#[macroquad::main("Audio Spam")]
async fn main() {
let mut s = Some(load_sound("mus.ogg").await.unwrap());
play_sound_once(s.as_ref().unwrap());
let deadline = get_time() + 2.0;
loop {
if get_time() > deadline && s.is_some() {
info!("dropping");
std::mem::drop(s.take());
} …
```
=> Fix sound memory leak

src/lib.rs, src/quad_gl.rs
This PR solves two problem: it makes possible to `draw_mesh` with Mesh larger than a draw call size, and it makes possible to reduce draw call size to save some memory.
=> graphics: Make draw call size adjustable

tiled/src/lib.rs, tiled/src/tiled.rs, tiled/src/tiled/layer.rs
Tiled supports several types of properties, not just strings. They are written as corresponding JSON values. `macroquad-tiled` isn't designed to handle that and will return a JSON parse error as it always expects a string. Not only it is somewhat frustrating, it doesn't allow to fully use the features of `Tiled`.
This PR fixes that by adding a special type to encode all valid property values. This type is sufficient to support all the types of properties that `Tiled` has.
The PR adds an enum type that has a custom deserialisation implementation, which is used instead of `String` for the `value` field of `Property`.
This PR also removes the duplicate `Property` definition.
The implementation DOES NOT verify if the `value` agrees with the `type`, as it is assumed that it shouldn't be done …
=> tiled: add flexible property value type

src/audio.rs, src/exec.rs, src/lib.rs, src/telemetry.rs, src/text.rs, src/texture.rs, src/ui.rs, src/ui/render/mesh_rasterizer.rs, src/ui/render/painter.rs, src/ui/widgets/checkbox.rs, src/ui/widgets/combobox.rs, src/ui/widgets/drag.rs, src/ui/widgets/editbox.rs, src/ui/widgets/input.rs, src/ui/widgets/label.rs, src/ui/widgets/popup.rs, src/ui/widgets/slider.rs, src/ui/widgets/tree_node.rs
Followup to #800: add missing semicolons at the end when nothing is returned, also remove some references that are redundant.
=> fix missing semicolons and redundant references

src/telemetry.rs
A warning for this was added in nightly and it is trivial to fix.
=> fix compiler warning for elided lifetime

src/color.rs, src/input.rs, src/lib.rs, src/math/circle.rs, src/quad_gl.rs, src/texture.rs, src/ui/widgets/editbox.rs, src/ui/widgets/slider.rs
Followup to #817: remove redundant local variables, wrapper closures, explicit returns, unneded early variable declarations and unneded (mutable) references.
=> use shorthand initialization and remove redundant variables

tiled/src/lib.rs
This change adds support for `tiled`'s flipping flags when rendering a tilemap
- Adds new api in Map `.spr_flip`, which renders a tile including the tile's [flipping parameters](https://doc.mapeditor.org/en/stable/reference/global-tile-ids/#mapping-a-gid-to-a-local-tile-id)
- Uses that api in .draw_tiles
From a simple test map I made:
| Before | After |
| ------ | ----- 
| ![image](https://github.com/user-attachments/assets/21ed53b8-dece-4e70-ae15-0377df41d6c7)|![image](https://github.com/user-attachments/assets/2b27ffff-b0bb-4d32-ba4d-7d1a3562dd95)|
=> macroquad-tiled: Support tile flipping & rotation in `Map::draw_tiles`

src/text.rs
Fixes a reference in docs to a non-existent example.
=> Update documentation reference for TextDimensions to fix #599.

src/texture.rs
Cleanup to follow-up on #838: it is not required to call `get_context` there anymore.
=> remove unused `get_context` call

src/camera.rs
I noticed that if you have a custom viewport set on your `Camera2D`, then `screen_to_world` does not work correctly because it always assumes the viewport is `(0, 0, screen_width(), screen_height())`. This change checks if there is a viewport and, if so, uses that instead. Let me know if you want this change; I've just had it in my local copy for a bit now.
=> respect viewport in Camera::screen_to_world

Cargo.toml
Mosty just bumps the [quad-rand](https://github.com/not-fl3/quad-rand) dependency to v0.2.3 so that consumers of macroquad can have access to the independent random generator instances and no_std compat support 👀
=> Bump quad-rand version to 0.2.3

examples/rustaceanmark.rs, src/time.rs
This PR adds `draw_fps` and `draw_frame_time` functions for drawing the result of `get_fps` and `get_frame_time`, respectively.
The rustaceanmark example was updated to use the newly added `draw_fps` function.
=> Add `draw_fps` helper function

src/camera.rs
Hi, thank you for such an awesome crate!
Currently `set_default_camera` does not reset viewport, so the following workaround needs to be used:
```rust
// Workaround to reset viewport
set_camera(&Camera2D::default());
set_default_camera();
```
This pull request fixes that.
=> Reset viewport in `set_default_camera`

src/lib.rs
This avoids some unsafe code and an explicit drop impl
=> Avoid a global mutable static

macroquad_macro/src/lib.rs
Just print an extra message if the `async` token is not found, similar to the case below in the code.
=> add help message for `#[macroquad::main]` on a non-async function

src/input.rs, src/lib.rs, src/prelude.rs
Adds drag and drop file support to Macroquad for #663. Note that this will only work through WASM until Miniquad supports drag and drop on other platforms. (I've just submitted a PR to add support for this on Windows to MIniquad: https://github.com/not-fl3/miniquad/pull/518)
=> Implement drag and drop file support

src/texture.rs
The current implementation of `build_texture_atlas()` ends up making an atlas, that ignores the default filtering mode. This PR remedies this situation by making `set_default_filter_mode()` also set the filter mode of the texture atlas.
The alternative to this fix is to introduce a new piece of API -- `set_texture_atlas_filtering()`
=> Make the texture batcher respect default mode

src/ui/widgets/checkbox.rs
fixes #902 
with this fix, now the checkbox shows up and responds with the position relative to window its in.
=> Updates the position of the checkbox relative to the window

src/lib.rs
Issue #681 is still valid for the latest `master` version of `macroquad`. This PR fixes the crash from this issue. The main reason it happens in the first place is as follows. Closes #681
Macroquad apps are generally structured in the following way:
```rust
#[macroquad::main("Your title")]
async fn main() {
loop {
draw_circle(screen_width() - 30.0, screen_height() - 30.0, 15.0, YELLOW);
next_frame().await;
}
}
```
When you exit `main` after `draw_circle` and alike, but before `next_frame()` -- the context of `macroquad` is left in a sort of bad state. It contains a lot drawcalls, but all the resources it points to are dead, because they were locals in `main()`. The event loop still calls `end_frame`, which causes `quad_gl.rs` to access a bunch of dangling references.
This implicit "zones" …
=> Fix Sudden Crash from Exitting Main Loop

src/camera.rs
Fixes #727.
Added fields `z_near` and `z_far` in Camera3D.
Removed constants `Camera3D::Z_NEAR` and `Camera3D::Z_FAR`.
=> Make Camera3D near and far fields customizable

Cargo.toml
`backtrace` had a breaking change in https://github.com/rust-lang/backtrace-rs/pull/615, where it removed old feature flags. This forces Cargo to fall back to an older version of `backtrace` (namely `v0.3.71`).
=> Fix backtrace dependency

src/text.rs
This addresses an issue where `draw_multiline_text_ex()` would incorrectly keep subsequent lines 'vertically flush' with the first line, when it should also rotate horizontally in order to given the visual presentation of a fully multi-line rotated text block on a **single render**.  Below screenshot is an example of what it should look like with a single draw, and yes I've tested this with animated spinning text.
Correct output:
This also removes the restriction of not supporting vertical fonts, as by default it should use the font size given as the offset.  (Tested with [NotoSansJP](https://fonts.google.com/noto/specimen/Noto+Sans+JP)).  Ideally, usage of `advance_height` would be handled as a separate `draw_text_vertical()` function or otherwise some kind of boolean flag. (not part of …
=> Fix multi-line text rendering for rotated text after first line

src/color.rs
Removes the claim that `Color::from_rgba` cannot be `const` because that is no longer the case, and updates why the `color_u8!` macro exists.
=> remove some inaccurate details in color documentation

src/math/rect.rs
Thanks to https://github.com/rust-lang/rust/pull/129195, all methods on `Rect` can become const now, including those with `&mut self`.
Also fixes a small bug where points on the border of a rect where not recognized to be in it, and adds a simple test for that.
=> make all `Rect` methods `const`, fix a small bug in `Rect::contains`

src/experimental/animation.rs
self-explanatory, makes the test compile again
=> add a missing `&` to a doctest

src/math/circle.rs, src/math/rect.rs
The same as #919, but for `Circle`.
Makes several methods that use `&mut self` const, fixes a few typos and adds documentation to several methods that did not yet have any.
Unfortunately, not all methods can be `const` yet, because `f32::sqrt` (used by `Vec2::distance`) is not `const`.
=> make several `Circle` methods `const` and add a few doc comments

examples/default_font.rs, src/text.rs
As a complement to `get_default_font`, this PR adds `set_default_font` as well as a small example to demonstrate that it works:
This makes it much easier to set the default font once before the main loop and then use the regular text drawing APIs, rather than having to explicitly use `draw_text_ex` with the font each time.
=> add `set_default_font` and a small example

src/color.rs, src/experimental/camera/mouse.rs
This allows more ergonomic conversions between colors, `f32` arrays and `u8` arrays, such as:
```rust
Color::from([16, 25, 116, 34]);
```
The `Into` implementations will be provided automatically, so all existing code continues to work.
The diff can also be reproduced with `cargo clippy --fix --lib -p macroquad`.
=> replace all `Into` implementations with `From` implementations

src/experimental/coroutines.rs
Previously, `Coroutine` was used, which is equivalent to `Coroutine<()>` due to the definition as `pub struct Coroutine<T = ()> { ... }`. 
This PR makes the function `stop_coroutine` generic over any result type instead.
Fixes #885.
=> add missing generic to `stop_coroutine`

src/experimental/coroutines/generational_storage.rs, src/experimental/scene.rs
Just another small code cleanup to replace 
```rust
if foo.is_none() {
return None;
}
foo.unwrap()
```
with 
```rust
foo?
```
in several places.
=> apply `clippy::question_mark` lint

src/experimental/coroutines/generational_storage.rs, src/experimental/scene.rs, src/experimental/scene/arena.rs, src/quad_gl.rs, src/tobytes.rs
`size_of` is already a part of the prelude since https://github.com/rust-lang/rust/pull/123168/ (1.80.0). Since we do not support versions this old anyway, the `std::mem::` prefixes can simply be removed.
=> use `size_of` from the prelude instead of `std::mem::size_of`

src/shapes.rs
This documents an alternative solution for people who want very accurate circles that are more precise than `draw_circle`.
cc #939
=> document alternatives for higher-precision circles

physics-platformer/src/lib.rs
Hey there! I'm working on a game right now using Macroquad and it's been great! However, I ran into the need to implement dynamically sized hit boxes based on various animation states (crouching for example). 
After reading the source code for the platformer lib, I realized that there needed to be some methods to set and get the actor size. 
Regarding "setting": to do this correctly, the actors position also needs to be changed based on the new height passed in otherwise the hit box would do weird things. You'll see that in the implementation. 
Let me know what you think!
=> Set and Get Actor Size

src/text.rs
Using `impl AsRef<str>` instead of `&str` allows you to pass in any type that can be viewed as a string slice, which makes for a more convenient API, as users don't have to to convert their types on their own. This also won't introduce any breaking API changes.
=> using impl AsRef<str> for more convenient api

src/ui/widgets/slider.rs
Adds the ability to configure the width of slider labels. For longer labels, the name typically gets clipped due to the small space allocated for them. This allows a custom width to be provided, mitigating the issue.
The "extraordinarily long label" gets clipped, but the larger label width for the slider below accommodates more text.
```rs
Window::new(hash!(), vec2(100., 100.), vec2(400., 400.))
.label("View")
.close_button(true)
.ui(&mut root_ui(), |ui| {
let mut a: f32 = 0.;
Slider::new(hash!(), 0. .. 1.)
.label("extraordinarily long label")
.ui(ui, &mut a);
Slider::new(hash!(), 0. .. 1.)
.label("Slider with label_width = 250")
.label_width(250.)
.ui(ui, &mut a);
});
```
=> Added configurable label width for sliders

src/lib.rs
This PR:
1. Closes #547 
4. Fixes a potential issue for mouse buttons
5. All active `key_down` issue `key_released` when the focus is lost
6. All active touches are released too
This PR fixes it for all platforms for all platforms, where `miniquad` issues `window_minimized_event`.
However, not-fl3/miniquad#552 will make this fix work for Windows and make it behave better on WASM.
=> fix the sticky key down

src/texture.rs
Part of the effort to patch the Rust-sec advisory report (https://rustsec.org/advisories/RUSTSEC-2025-0035.html)
Closes #746 by introducing an assert into the `unsafe` functions to avoid UB.
* `Image` already uses the `assert!()` liberally to check its invariants
* This will not harm the performance too much, as the user can always cache the reference
=> texture: add extra asserts to Image
