Cargo.toml
examples/camera.rs
src/camera.rs
src/drawing.rs
src/lib.rs
src/time.rs

Cleaned up crazy refactoring made during LudumDare :)
- sprites rotation
- camera modes
- ttf labels
- textures filtering
- enabled MSAA by default

Breaking changes in drawing api 

---

examples/asteroids.rs
src/shapes.rs

Hey, just created this asterodis example, also implemented the draw_poly, draw_poly_lines, draw_triangle and draw_triangle lines.
Also removed draw_hexagon since I don't see much value in it having draw_poly, but I could reimplement it using draw_poly if you think it's good to have.
One thing I'm not sure about is the signature of draw_triangle, I used 3 vec2 as parameters (similar to what raylib does) but in the rest of the draw functions we're using just f32 for x and y... maybe something to think about, I found it easier to use vec2 when i could, it has a bunch of useful methods, and adding a vec2() to the function calls if you just have f32s doesn't seem too bad for me.
Let me know what you think about it!

Asteroids example

---

src/exec.rs
src/lib.rs
src/texture.rs

With this, loading in game configuration is as simple as:
```rs
let config = serde_json::from_slice(&load_file("config.json").await.unwrap()).unwrap();
```

Add load_file and use it in load_texture

---

README.md

Updated to our correct logo :)

Update Embark Studios logo

---

Cargo.toml
examples/particles.rs
particles/src/lib.rs

This will make the CI check particles repo alongside with macroquad.

particles: Add example to macroquad /examples

---

Cargo.toml
examples/asteroids.rs
examples/basic_shapes.rs
examples/camera_transformations.rs
examples/logs.rs
examples/particles.rs
examples/post_processing.rs
examples/shadertoy.rs
particles/examples/particles.rs
particles/examples/single_emitter.rs
particles/src/lib.rs
quad-gl/Cargo.toml
quad-gl/src/lib.rs
src/camera.rs
src/collections.rs
src/collections/magic_vec.rs
src/input.rs
src/lib.rs
src/math.rs
src/models.rs
src/prelude.rs
src/shapes.rs
src/texture.rs

0.9 -> 0.10
`.x()` is still allowed, but will give a warning
but `.x` is now available! :tada:

Update glam version

---

examples/platformer.rs
physics-platformer/src/lib.rs

Area to check riding actors was bigger by 1 pixel :)

platformer: Fix off-by-one error

---

profiler/src/lib.rs
src/quad_gl.rs
src/telemetry.rs

This allows to pause and investigate the frame with a spike.

profiler: Show frames history graph

---

README.md

Having a few links to the docs is always nice.

Add docs badge and additional link to docs

---

examples/snake.rs

fix a bug in snake example, where you can kill yourself trying to move the snake in the opposite direction.

Check snake movement direction

---

src/experimental/coroutines.rs
src/experimental/scene.rs

Tweens got a massive refactor and now do not require raw pointers magic to work. Wich makes them safe to use and now if the tweening object got deleted during the tween - the tween would be stopped.
Stopped without a segfault!
Another change - coroutine's future is now Send.
With Send compiler will be a bit grumpier and will save us from Unwrap None panics on runtime.

coroutines: Make tweens safe

---

src/lib.rs

update mouse pos even in mouse button events to fix touch pos

---

src/texture.rs

A little quality of life improvement here, no trickery with negative dest width/height anymore :)

texture: Flip textures with flip_x/flip_y in DrawTextureParams

---

src/quad_gl.rs

* 512 is too little, it's run out of limit after couple of Mat4
Dependent PR in miniquad: https://github.com/not-fl3/miniquad/pull/183

quad-gl: make uniforms array dynamically sized

---

src/experimental/collections/storage.rs
src/experimental/coroutines.rs
src/quad_gl.rs
src/ui/render/painter.rs
src/ui/widgets/editbox/text_editor.rs

This PR adjusts some typos in code, previously mentioned in #185.
Some minor user code breakage might happen.

fix some typos in code

---

README.md

Closes #99 (_"Create "Awesome macroquad" list"_)

README: Add Communty section

---

.github/workflows/rust.yml
src/experimental/coroutines.rs
src/shapes.rs
src/ui/widgets.rs
src/ui/widgets/editbox.rs
src/window.rs

formatting should be runned by `cargo fmt --all` command

ci: add fmt

---

src/ui.rs
src/ui/widgets/drag.rs
src/ui/widgets/editbox.rs
src/ui/widgets/slider.rs

ui: fix bug with tab navigation between different windows

---

profiler/Cargo.toml
profiler/src/lib.rs

Currently `macroquad-profiler` is broken (not even on crates.io).
I updated the source to use `macroquad::ui` instead of `megaui-macroquad`

Fix profiler

---

Cargo.toml
src/lib.rs

Use `log` facade as logging implementation with `log-rs` feature

logging: Implement "log-rs" feature

---

src/file.rs

Small fix for iOS file loading.

Fixes iOS path

---

examples/asteroids.rs
src/color.rs
src/material.rs
src/ui.rs
src/ui/style.rs

It is considered idiomatic to avoid needless return statements.

Turn needless return statements into tail expressions

---

src/ui/widgets/window.rs

This change makes window close button working again.

Re-enable window close button

---

src/input.rs
src/lib.rs
src/ui.rs

fix for #244 
this behavior might be undesirable but I needed a quick fix and decided to share

seperate input queue for ui

---

particles/src/lib.rs
src/camera.rs
src/experimental/camera/mouse.rs
src/quad_gl.rs

Allow to limit a camera render to a viewport on the screen, nice for splitscreen games

camera: Viewport field

---

src/exec.rs
src/experimental/coroutines.rs
src/lib.rs

you merged too fast :D The debug assertions don't actually work. We'd have to manually support them in each future and that is a pain. Let's just remove them

Remove broken assertions and unused impls

---

src/math/rect.rs
src/shapes.rs

Happy to make edits to anything, I just tried to document the stuff that was initially unclear to me that I had to try out, such as if `Rect` is defined by its center or top-left.

Add docs to shapes & rectangle

---

src/input.rs

Scale mouse position with dpi

---

src/text/atlas.rs

Deleting old atlas texture when creating a new one

---

src/math/circle.rs

Made radius accessible in macroquad::math::Circle

---

Cargo.toml

force miniquad version

---

src/math/circle.rs

Fixed typo in the offset method description

Updated src/math/circle.rs to fix typo

---

README.md

Little things that are itching each time I visit these github-s. :sweat_smile:

README.md: consistent casing, minor punctuation and grammer fixes

---

particles/src/lib.rs

Fix particle blending

---

examples/life.rs

Instead of using nested for loops to initialize the cells, this PR instead uses an iterator.

In example game "life": use iterator for initializing cell states

---

src/text.rs

Ran the tests. All of the coroutine and back to the future tests segfaulted, but they were doing that after a fresh clone so I'm assuming they're supposed to.

derive(Debug, Clone, Copy) for TextDimensions

---

examples/arkanoid.rs

Fix text glitch in arkanoid example

---

src/ui/render/painter.rs

Fixing clipping and offset issues on high DPI displays

---

src/audio.rs
src/text.rs
src/ui/render/painter.rs
src/ui/widgets/editbox.rs

sorry:
made the android only used import conditional to overcome compiler warning

conditional import of get_quad_context

---

src/experimental/animation.rs

The animation API looks pretty good but lacking documentation.
This PR trying to fix this.

Add animation documentation

---

src/input.rs
src/lib.rs

It is the fix for my last pull request.

Adding mouse_delta_position function to Macroquad

---

src/camera.rs
src/color.rs
src/text.rs

Fixed some links to be clickable. Fixed some line breaks in the camera module.

Fixed some doc comments: links and linebreaks

---

src/shapes.rs

No longer alloc a Vec to store these three vertices

Store triangle vertices on the stack

---

examples/letterbox.rs

A letterbox example like the raylib one. This should address #341

A Letterbox example

---

src/input.rs

I don't know if `chars_pressed_ui` should be cleared aswell
Adds enhancement for #630

added clear_input_queue for #630

---

src/color.rs

`cargo fmt ---all` follow-up to #692 (apologies for missing this earlier!)

cargo fmt color.rs

---

src/input.rs
src/lib.rs

Save last mouse position at the end of frame

---

src/shapes.rs

I added `draw_rectangle_lines_ex` so far. Opinions are welcome.

add draw_rectangle_lines_ex

---

src/shapes.rs

Update shapes.rs, add draw_arc

---

src/lib.rs

Works on android and ios with [this PR](https://github.com/not-fl3/miniquad/pull/452)

Added schedule_update-s for touch events

---

src/lib.rs

Added mainly for [egui-macroquad to work with blocking_event_loop](https://github.com/birhburh/egui-macroquad/tree/blocking_event_loop)
But it may be convenient for other purposes

Added mouse_motion and mouse_wheel to UpdateTrigger

---

src/text.rs

`draw_text_ex` and `draw_text` now return `TextDimension` to avoid calculating text size using `measure_text` once again
I decided not to add `draw_character` and `measure_character` (as i wanted in my last issue #775), because `draw_text` and `measure_text` do a great job with drawing/measuring characters
Tested with my project (custom text input and other "fancy text")

Add `TextDimension` return type for `draw_text_ex` and small refactoring

---

src/text.rs

Im really sorry, but i just found out that i screwed up with `total_width` calculation order in `draw_text_ex` (#776)
Please merge this pull request, because i made a terrible mistake...

FIX: text drawing was broken! 

---

src/texture.rs

Fix default filter mode ignored by from_rgba8

---

examples/camera_transformations.rs
examples/events.rs
examples/first_person.rs
examples/shadertoy.rs
examples/ui.rs
src/error.rs
src/file.rs
src/material.rs
src/quad_gl.rs
src/texture.rs
src/window.rs
tests/back_to_the_future_coroutines.rs

style: simplify some statements for readability

---

src/color.rs

Small enhancement for Color, and new method to easily mutate colors in constants

Color fixes/utility method

---

src/lib.rs

replay window minimized and restored events
